@startuml
package "python3" {
     [python3] --> [python3-minimal]
         [python3-minimal] --> [python3.10-minimal]
             [python3.10-minimal] --> [libc6]
                 [libc6] --> [libgcc-s1]
                     [libgcc-s1] --> [gcc-12-base]
                     [libgcc-s1] --> [libc6]
                 [libc6] --> [libcrypt1]
                     [libcrypt1] --> [libc6]
             [python3.10-minimal] --> [libpython3.10-minimal]
                 [libpython3.10-minimal] --> [libc6]
                 [libpython3.10-minimal] --> [libssl3]
                     [libssl3] --> [libc6]
                     [libssl3] --> [debconf]
                         [debconf] --> [perl-base]
                             [perl-base] --> [libc6]
                             [perl-base] --> [libcrypt1]
                             [perl-base] --> [dpkg]
                                 [dpkg] --> [libbz2-1.0]
                                     [libbz2-1.0] --> [libc6]
                                 [dpkg] --> [libc6]
                                 [dpkg] --> [liblzma5]
                                     [liblzma5] --> [libc6]
                                 [dpkg] --> [libselinux1]
                                     [libselinux1] --> [libc6]
                                     [libselinux1] --> [libpcre2-8-0]
                                         [libpcre2-8-0] --> [libc6]
                                 [dpkg] --> [libzstd1]
                                     [libzstd1] --> [libc6]
                                 [dpkg] --> [zlib1g]
                                     [zlib1g] --> [libc6]
                                 [dpkg] --> [tar]
                                     [tar] --> [libacl1]
                                         [libacl1] --> [libc6]
                                     [tar] --> [libc6]
                                     [tar] --> [libselinux1]
                     [libssl3] --> [<debconf-2.0>]
             [python3.10-minimal] --> [libexpat1]
                 [libexpat1] --> [libc6]
             [python3.10-minimal] --> [zlib1g]
         [python3-minimal] --> [dpkg]
     [python3] --> [python3.10]
         [python3.10] --> [python3.10-minimal]
         [python3.10] --> [libpython3.10-stdlib]
             [libpython3.10-stdlib] --> [libpython3.10-minimal]
             [libpython3.10-stdlib] --> [media-types]
             [libpython3.10-stdlib] --> [mime-support]
                 [mime-support] --> [mailcap]
                     [mailcap] --> [perl]
                         [perl] --> [dpkg]
                         [perl] --> [perl-base]
                         [perl] --> [perl-modules-5.34]
                             [perl-modules-5.34] --> [dpkg]
                             [perl-modules-5.34] --> [perl-base]
                         [perl] --> [libperl5.34]
                             [libperl5.34] --> [libbz2-1.0]
                             [libperl5.34] --> [libc6]
                             [libperl5.34] --> [libcrypt1]
                             [libperl5.34] --> [libdb5.3]
                                 [libdb5.3] --> [libc6]
                             [libperl5.34] --> [libgdbm-compat4]
                                 [libgdbm-compat4] --> [libc6]
                                 [libgdbm-compat4] --> [libgdbm6]
                                     [libgdbm6] --> [libc6]
                             [libperl5.34] --> [libgdbm6]
                             [libperl5.34] --> [zlib1g]
                             [libperl5.34] --> [perl-modules-5.34]
                     [mailcap] --> [media-types]
                 [mime-support] --> [media-types]
             [libpython3.10-stdlib] --> [libbz2-1.0]
             [libpython3.10-stdlib] --> [libc6]
             [libpython3.10-stdlib] --> [libcrypt1]
             [libpython3.10-stdlib] --> [libdb5.3]
             [libpython3.10-stdlib] --> [libffi8]
                 [libffi8] --> [libc6]
             [libpython3.10-stdlib] --> [liblzma5]
             [libpython3.10-stdlib] --> [libmpdec3]
                 [libmpdec3] --> [libc6]
                 [libmpdec3] --> [libgcc-s1]
                 [libmpdec3] --> [libstdc++6]
                     [libstdc++6] --> [gcc-12-base]
                     [libstdc++6] --> [libc6]
                     [libstdc++6] --> [libgcc-s1]
             [libpython3.10-stdlib] --> [libncursesw6]
                 [libncursesw6] --> [libtinfo6]
                     [libtinfo6] --> [libc6]
                 [libncursesw6] --> [libc6]
             [libpython3.10-stdlib] --> [libnsl2]
                 [libnsl2] --> [libc6]
                 [libnsl2] --> [libtirpc3]
                     [libtirpc3] --> [libc6]
                     [libtirpc3] --> [libgssapi-krb5-2]
                         [libgssapi-krb5-2] --> [libc6]
                         [libgssapi-krb5-2] --> [libcom-err2]
                             [libcom-err2] --> [libc6]
                         [libgssapi-krb5-2] --> [libk5crypto3]
                             [libk5crypto3] --> [libc6]
                             [libk5crypto3] --> [libkrb5support0]
                                 [libkrb5support0] --> [libc6]
                         [libgssapi-krb5-2] --> [libkrb5-3]
                             [libkrb5-3] --> [libc6]
                             [libkrb5-3] --> [libcom-err2]
                             [libkrb5-3] --> [libk5crypto3]
                             [libkrb5-3] --> [libkeyutils1]
                                 [libkeyutils1] --> [libc6]
                             [libkrb5-3] --> [libkrb5support0]
                             [libkrb5-3] --> [libssl3]
                         [libgssapi-krb5-2] --> [libkrb5support0]
                     [libtirpc3] --> [libtirpc-common]
             [libpython3.10-stdlib] --> [libreadline8]
                 [libreadline8] --> [readline-common]
                     [readline-common] --> [dpkg]
                     [readline-common] --> [install-info]
                         [install-info] --> [dpkg]
                         [install-info] --> [libc6]
                 [libreadline8] --> [libc6]
                 [libreadline8] --> [libtinfo6]
             [libpython3.10-stdlib] --> [libsqlite3-0]
                 [libsqlite3-0] --> [libc6]
             [libpython3.10-stdlib] --> [libtinfo6]
             [libpython3.10-stdlib] --> [libtirpc3]
             [libpython3.10-stdlib] --> [libuuid1]
                 [libuuid1] --> [libc6]
         [python3.10] --> [media-types]
         [python3.10] --> [mime-support]
     [python3] --> [libpython3-stdlib]
         [libpython3-stdlib] --> [libpython3.10-stdlib]
}
@enduml